### ISSUE TITLE
shapeNetCar的问题

### ISSUE THREAD

**Issue by qiurongcan** [thuml/Transolver#3]
在shapenetCar的这个代码中，在train.py文件的，发现学习率调度器在每个batch中都调用一次，是否需要改成每个epoch更新一次。
其次是shapeNetCar的模型超参数是直接使用默认的嘛，或者是其他未公布的超参数，如果是的话是否可以提供，非常感谢！！
<img width="738" alt="image" src="https://github.com/user-attachments/assets/26d3d607-d75a-4ed8-9329-dcafea370ba5">
<img width="446" alt="image" src="https://github.com/user-attachments/assets/4fd4da62-39d9-4eb6-b423-8ca7225f7e26">

**Comment by wuhaixu2016** [comment]
您好，感谢关注。
（1）不需要，我们的实验是按照batch来确定的，请见https://github.com/thuml/Transolver/blob/main/Car-Design-ShapeNetCar/train.py#L83
（2）是的，我们使用的是默认参数
