### ISSUE TITLE
Cannot reproduce the results of the paper

### ISSUE THREAD

**Issue by lilux618** [thuml/Transolver#4]
I trained the model based on **Airfrans** data using the script provided in the github repository, and the model uses transolver, but the convergence is as shown in the figure below, and the loss decreases very slowly, which doesn't seem to be in line with the results mentioned in the paper. 
<img width="652" alt="FF6873C0-13D2-4437-AD62-F2D4BE024EF7" src="https://github.com/user-attachments/assets/b53ef525-ea5c-4717-9e6b-ee4c50244899">
Are there any parameters I should adjust?

**Comment by wuhaixu2016** [comment]
Hi, thanks for your experiment.

We do not report the training log in AirfRANS. As we stated in README.md, you can need to execute `bash scripts/Evaluation.sh` to test the model. The final performance will be saved in scores/score.json.

You do not need to change any parameter in our provided scripts. The final spearman coefficient of lift coefficient will be 0.9978234455861399 in our experiments.
