### ISSUE TITLE
Evaluation metrics of AirfRANS dataset

### ISSUE THREAD

**Issue by niladridutta2001** [thuml/Transolver#6]
PFA the json file corresponding to the evaluation script of AirfRANS benchmark. Can you explain how to interpret the obtained metrics as given in this file?
[score.json](https://github.com/user-attachments/files/18122402/score.json)

**Comment by wuhaixu2016** [comment]
Hi, thanks for using this repo. Roughly speaking, these metrics correspond to the performance for different physics fields and coefficients.

You can find the details from here: https://github.com/thuml/Transolver/blob/main/Airfoil-Design-AirfRANS/utils/metrics.py#L397-L415
