### ISSUE TITLE
How to interpret the results of Airtrans?

### ISSUE THREAD

**Issue by Karn3003** [thuml/Transolver#7]
Hi, I have run the scripts according to the readme file, but unfortunately, I don't know how to interpret the numbers as given in the paper. I am attaching the final score of the JSON output.

{
    "mean_time": [
        0.00011054761503937534
    ],
    "std_time": [
        1.269395246735519e-05
    ],
    "mean_score_vol": [
        [
            0.0905372569616884,
            0.061257140312809495,
            0.01231359591765795,
            0.05596966357901692
        ]
    ],
    "std_score_vol": [
        [
            0.0,
            0.0,
            0.0,
            0.0
        ]
    ],
    "mean_score_surf": [
        [
            0.0,
            0.0,
            0.016364467908861115,
            0.0
        ]
    ],
    "std_score_surf": [
        [
            0.0,
            0.0,
            0.0,
            0.0
        ]
    ],
    "mean_rel_p": [
        20.560375107601285
    ],
    "std_rel_p": [
        0.0
    ],
    "mean_rel_wss": [
        [
            202.16098344440576,
            271.37333342930725
        ]
    ],
    "std_rel_wss": [
        [
            0.0,
            0.0
        ]
    ],
    "mean_score_force": [
        [
            23.689024587304303,
            0.2940362516124826
        ]
    ],
    "std_score_force": [
        [
            0.0,
            0.0
        ]
    ],
    "spearman_coef_mean": [
        [
            0.009156228905722645,
            0.9763369084227107
        ]
    ],
    "spearman_coef_std": [
        [
            0.0,
            0.0
        ]
    ]
}

**Comment by wuhaixu2016** [comment]
Hi, please see this issue: https://github.com/thuml/Transolver/issues/6

**Comment by Karn3003** [comment]
Hi, thanks for clarifying. But why are some quantities have 2/4 value. It's confusing that's what I wanted to know how to interpret it as given in paper.

**Comment by wuhaixu2016** [comment]
Thanks for detailing your question. As we stated in Page 16 of our paper "In the main text, we focus on the lift coefficient estimation and the pressure quantity on the volume and surface, which is essential to the take-off and landing stages of airplanes."

For Table 3, VOLUME is the third value of "mean_score_vol", Surf is the third value of "mean_score_surf", "C_L" is the second value of "mean_score_force" and \rho_L is the second value of "spearman_coef_std".
